### PR TITLE
Update glueviz version to 0.9.1

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by astrofrog** [comment]
@bsipocz - just out of curiosity, how does this repo handle it when I update builds of glueviz? For instance, I'm currently making a new build for v0.9.0 - how can I trigger that to be copied over here?

**Comment by bsipocz** [comment]
I'm not sure you can trigger there, the version number here needs to be updated.  

@mwcraig knows the details of the copying, I'm merely updating the versions. However #71 is a serious issue with the copying, and that is the reason for the PR (originally I wanted to update only astroquery, but that build is failing because of the new glueviz version).

Anyway, writing a script/bot that regularly inspects the dashboard and opens PRs here for new versions is on my list, but probably it won't happen before a hackday :)

**Comment by bsipocz** [comment]
@astrofrog - Oh, you mean that you are right now in the middle of uploading the new gluviz versions? In that case, restarting the failing appveyor/travis builds would be enough here.

**Comment by astrofrog** [comment]
@bsipocz - yes, I'm making a new build for 0.9.0 and it should be done soon.

**Comment by bsipocz** [comment]
@astrofrog @mwcraig - Any idea about this error?

https://travis-ci.org/astropy/conda-channel-astropy/jobs/167008821#L2461

```
The command "extrude_recipes requirements.yml" exited with 0.

34.01s$ if [[ -d recipes ]]; then conda build-all recipes --matrix-conditions="python $PYTHON_BUILD_RESTRICTIONS" --inspect-channels conda-forge astropy $UPLOAD; fi

Using Anaconda API: https://api.anaconda.org

Fetching package metadata ...........

Resolving distributions from 36 recipes... 

Traceback (most recent call last):

  File "/home/travis/miniconda/bin/conda-build-all", line 11, in <module>

    load_entry_point('conda-build-all==1.0.0', 'console_scripts', 'conda-build-all')()

  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build_all/cli.py", line 90, in main

    b.main()

  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build_all/builder.py", line 251, in main

    all_distros = self.compute_build_distros(index, recipe_metas, build_config)

  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build_all/builder.py", line 224, in compute_build_distros

    index[distro.pkg_fn()] = distro.info_index()

  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build_all/resolved_distribution.py", line 64, in with_vn_mtx_setup

    return orig_result(*args, **kwargs)

  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 697, in info_index

    d.update(self.app_meta())

  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 657, in app_meta

    self.path, self.get_value('app/icon')))

  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/utils.py", line 144, in md5_file

    return hashsum_file(path, 'md5')

  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/utils.py", line 134, in hashsum_file

    with open(path, 'rb') as fi:

IOError: [Errno 2] No such file or directory: u'/home/travis/build/astropy/conda-channel-astropy/recipes/glueviz/logo.png'

```

**Comment by astrofrog** [comment]
By the way, there is another pending build of glue which should be done soon (0.9.0 build 2)

**Comment by astrofrog** [comment]
Oh, also, glue now depends on QtPy and the version in defaults is not recent enough, so we need to use the one from conda-forge - and there is also a dependency on a plugin package `glue-vispy-viewers` which will need to be added here too

**Comment by bsipocz** [comment]
@astrofrog - dependencies are picked up from conda-forge, so that shouldn't be a problem, but nevertheless this seems a bit nontrivial, so I go ahead with a workaround for #86, so there won't be any rush to fix this PR.

**Comment by mwcraig** [comment]
The remaining fail here is due to the (silly) way that I set up a recipe for packages on conda-forge (I just copy the recipe), but glue references the logo file in its recipe, so needs that too. Short term fix: recipe template. 

Long term fix: Let's discuss here: https://github.com/OpenAstronomy/conda-channel/pull/23

**Pull request merged**
