### PR TITLE
Update reproject package to v0.3

### PR DESCRIPTION
**Pull request by astrofrog**

### CODE REVIEW

**Comment by mwcraig** [comment]
@astrofrog -- could you please try changing the first part of the URL in the recipe template for reproject from `pypi.python.org` to `pypi.io`?

**Comment by astrofrog** [comment]
@mwcraig - done! By the way, I've also opened a PR to add this to conda-forge: https://github.com/conda-forge/staged-recipes/pull/978

**Comment by mwcraig** [comment]
Excellent! At scipy next week I'm planning to focus on conda build stuff, including automation of the transfer of builds from one channel to another.

**Comment by bsipocz** [comment]
Thanks @astrofrog. 

I'll go ahead and change all those urls for the rest of the recipe templates.

**Comment by astrofrog** [comment]
@mwcraig - let me know if I can help - I'll be at SciPy too :)

**Comment by astrofrog** [comment]
I need to update this to v0.3.1...

**Comment by mwcraig** [comment]
> let me know if I can help - I'll be at SciPy too :)

Have no fear, @astrofrog, I will!

**Comment by bsipocz** [comment]
@astrofrog - Could you bump the version here to 0.3.1?

I'm not sure what's going on on appveyor, but I'm sure @mwcraig has an understanding of it.

**Comment by mwcraig** [comment]
@astrofrog -- this will need a rebase once I've switch over to conda-build-all. Working on that now...

**Comment by mwcraig** [comment]
@astrofrog -- I'm cherry-picking your commits over to #12

**Comment by astrofrog** [comment]
@mwcraig - sorry for not replying on any of the issues - I got sucked in to a couple of sprints. Thanks for working on all this! :)

**Comment by bsipocz** [comment]
reproject got updated to 0.3.1 by #12 and #52, so I'm closing this.

**Pull request closed without merging**
