### PR TITLE
Increase number of numpy builds

### PR DESCRIPTION
**Pull request by mwcraig**
Feel free to merge if this passes, @bsipocz

### CODE REVIEW

**Comment by bsipocz** [comment]
Travis didn't pick it up.

**Comment by bsipocz** [comment]
Also the linux builds are more important for our CI, so leave the windows builds unless the fail is something trivial to fix.

**Comment by mwcraig** [comment]
I think the travis fails here are spurious, restarting again.

Note that there will be an issue with trying to support old numpy (e.g. 1.7) + new python (3.5 maybe, 3.6 definitely) because continuum won't build numpy that old. For python 2.7 it is not an issue because continuum already has those older numpy builds for 2.7.

**Comment by mwcraig** [comment]
@bsipocz -- any guesses about the issue here: https://travis-ci.org/astropy/conda-channel-astropy/jobs/148089495#L2414

It occurs after several other builds already succeeded, which is odd...

**Comment by bsipocz** [comment]
@mwcraig - Any chance you could rebase this? A few changes has been made since, so I see some probability that this will pass :)

**Comment by mwcraig** [comment]
@bsipocz -- done. That was easily to most painless rebase ever 😄

**Comment by bsipocz** [comment]
@mwcraig - Could you add the ``astropy-ci-extras`` channel to the list? For old, e.g. 1.8 numpy astropy has to be picked up from there.

**Comment by bsipocz** [comment]
Could you please rebase this? There are some trivial conflicts.

Also I wonder whether it would be an easy hack to add to skip the numpy versions/astropy combinations that are not available on either default/conda-forge/astropy-ci-extras? This PR is failing on the fact that for osx we don't build astropy with older numpy versions. I think it would be OK to skip those anyway.

**Comment by mwcraig** [comment]
Rebased, not sure how to restrict to only the numpy/python combinations that continuum builds, though. Will try to come up with something.

**Comment by bsipocz** [comment]
This is passing now (one of the windows builds had a fluke, but it should be OK after merge, too).

**Pull request merged**
