### PR TITLE
Update keyring version to 9.3.1

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by mwcraig** [comment]
Looks like keyring has added a dependency: `secretstorage`

**Comment by mwcraig** [comment]
And secretstorage is not on defaults or conda-forge, so try adding it to `requirements.yml`....

**Comment by bsipocz** [comment]
And now dbus-python is the missing one. 

However in the meantime I saw that keyring is also built on conda forge. Do we already look for packages there? If yes, maybe we can remove its build from here, as we only do it as it's a dependency for astroquery (and I can update the ci files in astroquery to use the conda-forge channel, too).

 https://anaconda.org/conda-forge/keyring/files

**Comment by mwcraig** [comment]
Two options, it looks like:
- Add `include_extras: false` to requirements here, or
- Open a PR to update the conda-forge version of keyring to 9.3.1

The first option will fix the issue here because `secretstorage` is listed as an extra in setup.py. The second will solve it because `extrude_recipes` now looks for a package in conda-forge if there is not a recipe template for it, and conda-build-all will copy from one channel to another, so we'd end up with the conda-forge version.

**Comment by mwcraig** [comment]
Wait, just realized we do have a recipe template, so the include_extras stuff doesn't matter, because we don't end up calling `conda skeleton` in that case.

**Comment by mwcraig** [comment]
Since `secretstorage` is an optional Linux-only dependency, how about removing it entirely?

**Comment by mwcraig** [comment]
One other alternative:
- delete the recipe template for keyring
- change the version to match the one on conda-forge

With those changes the astropy channel stuff will pick up the current conda-forge build.

**Comment by mwcraig** [comment]
To get past this quickly, how about dropping the version number to `9.0` and removing the recipe template? That will get us that version from conda-forge, at least.

**Comment by bsipocz** [comment]
So, now it seems that taking the conda-forge recipe is not working for some reason either:
https://travis-ci.org/astropy/conda-channel-astropy/jobs/147036079#L852

**Comment by mwcraig** [comment]
😭 

So it turns out I'm just copying `meta.yaml` and hoping for the best. `keyring` needs a patch, so the build fails.

I found out on Friday that if I delete and recreate the current packages in `anaconda.org/astropy` I can copy the build packages from conda-forge to astropy (no clue why that is necessary, but it works).

Sooo....in the interest of moving this along, I just copied keyring to astropy from the command line. Restarting the CI jobs, and tomorrow will look at fixing up any broken packages on astropy and re-enabling copying. I have it running on openastronomy right now without any issues.

**Comment by mwcraig** [comment]
Merging before something else breaks.....

**Pull request merged**
