### PR TITLE
Add halotools

### PR DESCRIPTION
**Pull request by mwcraig**
Replaces https://github.com/astropy/conda-builder-affiliated/pull/96

### CODE REVIEW

**Comment by mwcraig** [comment]
Cancelled builds since this was just a rebase of a successful build.

**Comment by bsipocz** [comment]
Thanks @mwcraig!

cc @aphearin - halotools will be available on conda.

**Comment by mwcraig** [comment]
@aphearin -- either of these will work for installing: `conda install -c astropy halotools` or `conda install -c openastronomy halotools`.

**Comment by aphearin** [comment]
This is great! Thanks @mwcraig and @bsipocz! 

So I'm currently finishing up my next minor release, v0.2. When I get it up on pip, should I then submit a PR making the change to `requirements.yml` to change the `requirements` flag to `0.2`?

**Comment by bsipocz** [comment]
@aphearin - Yes, and also remove the python version restriction ;)

**Pull request merged**
