### PR TITLE
Update astroscrappy version to 1.0.5

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by mwcraig** [comment]
Restarted failing builds because they they seemed to have been caused by download issues.

**Comment by mwcraig** [comment]
Travis mac fail is due to a failure of emcee to build on conda-forge (so a copy from conda-forge fails). [now fixed on conda-forge, so restarted the failed build here]

Windows fail is because applying the patch fails, will try to take a look this week.

**Comment by bsipocz** [comment]
Thanks @mwcraig for taking this over. I'm away this week, but ping me if needed and I'll deal with it once I'm back.

**Comment by mwcraig** [comment]
@bsipocz -- though this has green lights, please hold off on merging. I want to try a couple more mac-related configuration changes.

**Comment by mwcraig** [comment]
Merging this...not entirely sure that the binaries will run on Mac OSX 10.9, but also not sure that matters...

**Comment by mwcraig** [comment]
@bsipocz -- you may need to rebase the other PRs; there was one important change in here in the travis configuration: bumping defaults to the top of the priority list. Without it, we were picking up a very old version of conda from conda-forge (actually, it may not be absolutely necessary now since that package has now been updated on conda-forge, but this should help protect against future issues).

**Pull request merged**
