### PR TITLE
Pin conda build, update astroplan version 

### PR DESCRIPTION
**Pull request by mwcraig**
Hopefully pinning will temporarily fix the build issues seen in #74

### CODE REVIEW

**Comment by bmorris3** [comment]
Let me know if there's anything I can do to help.

**Comment by mwcraig** [comment]
I'm going to try a local Windows build to track down the issue...I'm a little surprised it succeeded on python 2.7 and 3.4 but failed on 3.5.

**Comment by mwcraig** [comment]
Worked locally, so I've restarted the appveyor build...no luck. The fail is here: https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.248#L2905

Checking to see if reducing the number of builds helps...

**Comment by mwcraig** [comment]
@bmorris3 -- the build succeeded, so conda packages should be available soon.

**Comment by bmorris3** [comment]
Thanks @mwcraig!

**Comment by mwcraig** [comment]
Unfortunately, the upload script now appears to be broken (it only uploads on merges, not PRs)...so it will still be a little while.

**Comment by mwcraig** [comment]
Working now, uploads are in progress...

**Comment by bmorris3** [comment]
Seems to be up! Thanks again @mwcraig

**Comment by mwcraig** [comment]
FYI, I'm about to delete the astroplan 0.1 builds because the links for them don't work (not sure why, but packages built more than ~several months ago mostly seem to have broken links).

**Pull request merged**
