### PR TITLE
Update aplpy version to 1.1.1

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by bsipocz** [comment]
@astrofrog - aplpy is not tested with appveyor. Is it supposed work without problems on windows? Current builds on py2.7 and py3.4 are failing, but I haven't yet investigated the reason.

**Comment by mwcraig** [comment]
Looks like pyqt: https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.258/job/rrs7mboxyeop5hom#L1046

**Comment by bsipocz** [comment]
Thanks @mwcraig. Clearly I would better pay full attention to the talks here, rather than do half baked jobs in the meantime.

**Comment by astrofrog** [comment]
@bsipocz - APLpy pre-dates appveyor and I never got a chance to configure it properly, but we should add it!

**Comment by mwcraig** [comment]
@bsipocz  -- the appveyor problem is that the log output seems out of sync with the ending error messages. I spent too much time over the weekend reading them 😃

**Pull request merged**
