### PR TITLE
add pyspeckit to conda channel

### PR DESCRIPTION
**Pull request by keflavich**

### CODE REVIEW

**Comment by keflavich** [comment]
Same issue here: astropy-helpers isn't installing
https://travis-ci.org/astropy/conda-channel-astropy/jobs/120104309#L768

**Comment by mwcraig** [comment]
@keflavich -- again, sorry for the delay. Same fix:  please add this line to the `requirements.yml` entry for pyspeckit:

```
setup_options: '--offline'
```

**Comment by mwcraig** [comment]
Will add do a PR on your branch to add a recipe template. `conda build` tries, by default, to import every module in your package as part of its testing, but is failing on importing the test module because pytest isn't listed as a dependency (and it shouldn't be, since it isn't required for using the code).

**Comment by mwcraig** [comment]
@keflavich -- I'm hitting a couple problems when I try to build locally, one set because of print statements in pyspeckit itself (see pyspeckit/pyspeckit#169) and the other set because of errors in the tests.

The first set will need to get fixed before we can get this building; if you need to get the conditions build done right away I could generate a patch to get it building, or you can do a new release with pyspeckit/pyspeckit#169.

The errors I hit in the tests (which I realize is a separate git submodule) are:

```
Compiling /Users/mcraig/anaconda/envs/_build/lib/python2.7/site-packages/pyspeckit/tests/olivier_plot.py ...
  File "/Users/mcraig/anaconda/envs/_build/lib/python2.7/site-packages/pyspeckit/tests/olivier_plot.py", line 126
    with open(filename 'a') as f:
                         ^
SyntaxError: invalid syntax

Compiling /Users/mcraig/anaconda/envs/_build/lib/python2.7/site-packages/pyspeckit/tests/test_hr2421_interactive.py ...
  File "/Users/mcraig/anaconda/envs/_build/lib/python2.7/site-packages/pyspeckit/tests/test_hr2421_interactive.py", line 73
    raw_input('Press enter to print(guesses and best fit and end code'))
                                                                       ^
SyntaxError: invalid syntax

Compiling /Users/mcraig/anaconda/envs/_build/lib/python2.7/site-packages/pyspeckit/tests/test_nh3_multi.py ...
  File "/Users/mcraig/anaconda/envs/_build/lib/python2.7/site-packages/pyspeckit/tests/test_nh3_multi.py", line 78
    sp.specfit.plotresiduals()
     ^
SyntaxError: invalid syntax
```

**Comment by keflavich** [comment]
Thanks.  These tests aren't run, apparently, but they probably should be.  I've pushed fixes & merged your PR.

**Comment by mwcraig** [comment]
Two options now, no strong preference on my part:
1. You could do a new release of pyspeckit, then update the version number in requirements.
2. I can come up with patches that will allow the current version to build.

**Comment by keflavich** [comment]
I'll make a new release, but it will be a few days (want to get one more feature in....)

**Comment by keflavich** [comment]
I've made a new release, but I can't get it onto pypi.  I kept getting HTTP 400 errors, then I tried changing something, and now I get other errors for which google is unhelpful.  I'll try again tomorrow under the (inevitably incorrect) assumption that pypi was just busted.

**Comment by mwcraig** [comment]
The joy of packaging...

**Comment by bsipocz** [comment]
@keflavich - Could you please rebase? I see the 0.1.19 version on pypi, but the requirements.yml file has changed since in master.

**Comment by mwcraig** [comment]
I'm going to close this and star from scratch...a lot has changed in 3 years!

**Pull request closed without merging**
