### PR TITLE
Update gammapy version to 0.4

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by mwcraig** [comment]
Fails here are because at pyastro16 I added the option `--all-extras` to `conda-skeleton` in this [line in extruder](https://github.com/astropy/conda-build-tools/blob/master/extruder/extrude_recipes.py#L328).

@cdeil -- do you want the conda package for astropy to require all of the extras? adding them isn't a big deal, but if you prefer we can leave them out.

edit:

The additional packages we would need to pull in are:
- flask-bootstrap
- flask-nav
- sherpa

**Comment by bsipocz** [comment]
I've added the flasks to the package list, though I'm not sure what to do with sherpa. They don't have any new releases on pypi, though they maintain a conda channel (called sherpa). Could we use that somehow?

**Comment by mwcraig** [comment]
`conda-build-all` will look in `inspect-channels` and copy packages to the `upload-channel`, so in principle copying will work.

Looks like the sherpa github repo has a recipe we could use as a template instead (or in addition)...

**Comment by mwcraig** [comment]
Turns out the `--all-extras` flag being used by default is a problem because it breaks all Windows build. I'll either back that out or add a way to prevent it.

**Comment by cdeil** [comment]
@mwcraig @bsipocz  - Thanks for working on this.

I had a Gammapy poster last week and a few people accidentally conda installed the very old Gammapy 0.3 version. So it would be great if an 0.4 version were available.

As we discussed before, ideally there would be one "gammapy-core" version that just depends on Numpy and Astropy, and an "gammapy" version the depends on other things. Alternatively these could also be named "gammapy" and "gammapy-all".
I think this is non-trivial to set up and is what has been holding up the Gammapy 0.4 conda package? Maybe for now just make one conda package in the same way as for the 0.3 release?

(not many users will want the the flask packages as dependencies, OK to just ignore those for now.)

**Comment by mwcraig** [comment]
@cdeil -- I _should_ have the necessary changes ready soon (as in today) in #12. The relevant change is not requiring all the extras. 

If that PR is still stuck after lunch I'll work up a recipe template for gammapy 0.4 with no extras to get that in, and a meta-package (which is just another package to your users) for gammpy-all. The metapackage won't be available on Windows because sherpa isn't on Windows.

**Comment by mwcraig** [comment]
@bsipocz -- thanks for the update!! Looks like the fail is when it tries to `import gammapy.scripts.spectrum_pipe`. Can you generate a recipe template to skip that or should I? You will need the latest modified version of conda-build from astropy-ci-extras

**Comment by bsipocz** [comment]
@mwcraig - I've never made a recipe template, so it's faster if you do it, or walk me through on gitter.

**Comment by mwcraig** [comment]
I'll go ahead and do it...right now installing the custom conda-build is a little bit of a hassle. Will open a PR on your PR.

**Comment by mwcraig** [comment]
@cdeil -- there are a couple of issues here that I'll need your input on to resolve. 

First the explanation:

The fail in this particular build is real: `spectrum_pipe` is listed as an entry point in at https://github.com/gammapy/gammapy/blob/v0.4/setup.cfg#L38 but there is is no `spectrum_pipe` in scripts.

In addition, using a newer version of conda-build,  at least some scripts are constructed incorrectly, I think because the import situation is confusing.

One of the scripts, for example, is `gammapy-info`. 

The entry point that conda is constructing from setup.py is ` gammapy.scripts.info:info_main`, but `gammapy.scripts.info` is both a module and a function because `gammapy.scripts` imports the *function* info from the *module* `info`. 

Somehow setuptools manages to get this right and the old version of conda-build in this particular PR doesn't choke on this, but the latest version of conda-build does fail, and the import structure seems confusing.

**Questions:**

1. Should I get `gammapy` working by just skipping `spectrum_pipe` (and any other scripts that fail)? I'm assuming yes and will try pushing that....
2. How should I handle the import issue? Would you be willing to do a patch release?

**Comment by bsipocz** [comment]
Thanks @mwcraig. Hopefully this will now pass.

**Comment by mwcraig** [comment]
Fingers crosseed, heading out to lunch for a bit...

**Comment by mwcraig** [comment]
@bsipocz -- could you please remove the `image-pipe` entry point and import test?

@cdeil -- looks like another entry point should be removed from `setup.cfg`

**Comment by mwcraig** [comment]
Almost there, just this: https://travis-ci.org/astropy/conda-channel-astropy/jobs/145267353#L4565

**Comment by bsipocz** [comment]
OK, so we can build with <3.5.2 (I'll do it once I get home), and it seems that @cdeil needs to make a minor release with the configparser fix to have a py3.5 version.

**Comment by cdeil** [comment]
@bsipocz @mwcraig - Thank you!

We'll not make a bugfix Gammapy 0.4.1 release.
We plan to release Gammapy 0.5 this week.

Concerning the issues mentioned in this thread with outdated `setup.cfg` entry points: would it be possible to add a travis-ci build that notices such issues to make sure `master` is always OK and such errors are caught before making releases int the future?

**Comment by bsipocz** [comment]
The master was fine at the time of release, the new python came out later I
think.

**Pull request merged**
