### PR TITLE
Update CI to use channel copying

### PR DESCRIPTION
**Pull request by mwcraig**
This PR is the next step in moving builds over to conda-forge. I'm expecting the packages to be copied to include several win32 builds of reproject (and maybe others).

@bsipocz -- if this passes, let's merge it, and then, if the merge passes, I'll set up a cron job. There is an astroscrappy recipe PR open on conda-forge, so that will be the next test of the infrastructure (astroscrappy doesn't have builds for recent numpy/python I think).

Nothing should really change in the short run; I'll put together a plan for migrating recipes.

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @mwcraig! In the meantime do you have any idea what went wrong for astroquery? It had a post release, and now the copy doesn't work for it:
https://github.com/astropy/conda-build-tools/issues/26

**Comment by mwcraig** [comment]
Two questions, @bsipocz:

1. Do you want to be a maintainer on the recipes at conda-forge? Workload isn't much beyond updating version and checksum.
2. Should the tool copy over all versions for a package or only versions newer than whatever is currently on astropy?

**Comment by bsipocz** [comment]
1) I don't mind. I can open PRs either case, but probably it won't hurt to be able to hit the merge, too.
On the other hand we probably want to come up with a more automatized method at some point that picks up updates on pypi and opens automated PRs (I meant to do that here, but hasn't yet finished).

2) probably it won't hurt to copy over everything, I guess it's not much an overhead compared to copying over only the newer version.

**Comment by mwcraig** [comment]
Merging, let's see what happens....

**Pull request merged**
