### PR TITLE
Update halotools version to 0.2

### PR DESCRIPTION
**Pull request by bsipocz**
cc @aphearin

### CODE REVIEW

**Comment by aphearin** [comment]
Thanks @bsipocz!

**Comment by mwcraig** [comment]
Windows error is because one of the paths is over 256 characters (yeah, windows has that limit unless a special set of characters is prepended to the path).

Likely related to https://github.com/conda/conda-build/pull/260, which I guess I need to come back around to sooner than I thought.

**Comment by bsipocz** [comment]
How should be proceed then?
 I think we can easily live without the windows build, but would be great to get the linux versions available before AAS.

**Comment by mwcraig** [comment]
Ah, in that case, add this to `requirements.yml`:

```
  excluded_platforms:
      - 'win-64'
```

If it doesn't fix I'll get a different workaround going today.

**Comment by mwcraig** [comment]
@bsipocz -- you should be able to merge things now ;). Feel free to merge this once it passes if I don't get to it soon enough.

**Comment by bsipocz** [comment]
@mwcraig - Thanks. 

Re merging: if a package update passes, can it be merged? (and then it will automatically generate the conda packages in the channel?)

**Comment by mwcraig** [comment]
Yes; if it a package with a recipe template I sometimes check whether I can get rid of the template.

**Pull request merged**
