### PR TITLE
Include extras when building astroplan

### LINKED ISSUE #76: Can't find astroml-0.3 package
Running 'conda install astroml' under a python 2.7 installation of Anaconda 3.0 currently results in:

```
conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/astropy/osx-64/astroml-0.3-py27_0.tar.bz2: https://conda.anaconda.org/astropy/osx-64/astroml-0.3-py27_0.tar.bz2
```

I can workaround this using:

conda install -c astropy astroml=0.3

which succeeds in installing astroml-0.3-0.3-np19py27_0 (and not astroml-0.3-py27_0).

### PR DESCRIPTION
**Pull request by mwcraig**
This is a precursor to merging https://github.com/astropy/conda-build-tools/pull/20

Edit: closes #76 as a side effect

### CODE REVIEW

**Comment by mwcraig** [comment]
@bmorris3 -- any concerns about doing this? It would add the extras in setup.py (matplotlib and sphinx_rtd_theme) as hard requirements for the astroplan conda package. It would not affect people who pip install. Both matplotlib and sphinx_rtd_theme are available in the defaults channel, so installation should not be an issue.

**Comment by mwcraig** [comment]
Merging, since this won't actually trigger an astroplan build and it fixes astroml...

**Comment by bmorris3** [comment]
@mwcraig I don't fully understand the implications but it seems ok to me.

**Comment by mwcraig** [comment]
Basically it means that `conda install -c astropy astroplan` will be equivalent to `pip install astroplan[all]` (at least I think that is how you get the extra dependencies with pip). In your case the extra dependencies are `matplotlib` and `sphinx_rtd_theme`

**Pull request merged**
