### PR TITLE
bump sncosmo to v1.3.0

### PR DESCRIPTION
**Pull request by kbarbary**

### CODE REVIEW

**Comment by mwcraig** [comment]
@kbarbary -- thanks, not sure what the underlying cause of the fail is. Will take a look this weekend.

**Comment by mwcraig** [comment]
@bsipocz -- just a heads up that all of these PRs are likely to fail because this repo is still using an ancient version of conda-build. Can spend some time tomorrow afternoon on it...

**Comment by bsipocz** [comment]
@mwcraig - As I see the main problem is not the conda-build, but that there is a new 3.5 release that has a change to configparser, and some of the recent releases don't have a fix in for that yet. 

Here it seems like that the pypi link is not correct in the recipe. I'm not sure when and why it got changed.

**Comment by mwcraig** [comment]
In sncosmo's case, ~~the recipe is generaton from `conda skeleton pypi`, and the pypi URls have changed since conda-build 1.18.1 (which is what is being used at the moment). At least I'm pretty sure that is the issue here.~~

Agreed, it is odd that the URL has changed. I know pypi download URLs have changed (in the skeletoned recipes you can see some examples).  `conda-forge` has switch to using `pypi.io` as the domain, but putting that in a browser doesn't seem to work either...though 1.3.0 is there.

**Comment by bsipocz** [comment]
@kbarbary - Could you please rebase? Some links got changed in master, so this would probably work now.

**Comment by kbarbary** [comment]
Thanks. I'm actually going to release a bugfix sncosmo version (1.3.1) soon, so I'll just close this and open a new PR for v1.3.1.

**Pull request closed without merging**
