### PR TITLE
Update regions to 0.2

### PR DESCRIPTION
**Pull request by bsipocz**
cc @cdeil

### CODE REVIEW

**Comment by cdeil** [comment]
@bsipocz - Thank you!

**Comment by cdeil** [comment]
There's only regions 0.2 conda packages for Windows here:
https://anaconda.org/astropy/regions/files

No regions 0.2 conda packages for Mac and Linux?

**Comment by bsipocz** [comment]
@cdeil - I run into troubles with the conda packages. Not sure that I'll have time today or tomorrow to sort it out, but will do it on Sunday the latest.

**Comment by cdeil** [comment]
So just to confirm -- for me this works on Mac:
```
conda install regions
python -c 'import regions; regions.test()'
```
@bsipocz  - Thank you very much!

**Comment by bsipocz** [comment]
Actually it was @mwcraig who did the fix!

**Pull request merged**
