### PR TITLE
Adding spherical-geometry v1.0.6

### PR DESCRIPTION
**Pull request by bsipocz**
This seems to be the first version with source code uploaded to pypi.

### CODE REVIEW

**Comment by mwcraig** [comment]
The Windows fail is real, can do a fix Monday (unless you beat me to it). Looks like adding this in the appropriate place in `spherical-geometry` will do the trick: `#include <algorithm>`. 

See [this appveyor line](https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.71/job/9qc2tgiwjvyffst2#L774) for the fail, and this [random link from the appropriate google search](http://pqxx.org/boilerplate/frozen/279.html) for the fix.

**Comment by bsipocz** [comment]
There is no rush, especially with windows issues. 
I try to look into the corner issue in the next 30 mins before falling asleep :)

**Comment by mwcraig** [comment]
Already taking a look, seems like numpy is actually required but isn't
listed.

**Comment by mwcraig** [comment]
Maybe skip Windows for now: https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.186#L1554

**Comment by mwcraig** [comment]
Merging....

**Comment by bsipocz** [comment]
@bernie-simon - FYI:  we now have a conda package for the latest release of `spherical-geometry`, that got uploaded to PyPI, in the `astropy` channel.

**Pull request merged**
