### PR TITLE
Update requirements.yml

### PR DESCRIPTION
**Pull request by crawfordsm**
update version of ccdproc

### CODE REVIEW

**Comment by crawfordsm** [comment]
Finally ran, but seems to be some problem with `extrude_recipes` 

extrude_recipes requirements.yml
/home/travis/build.sh: line 45: extrude_recipes: command not found

**Comment by mwcraig** [comment]
Ok, will check in a little bit.

**Comment by mwcraig** [comment]
The issue is with the way the new version of conda handles dependencies when removing packages. Working on a fix....

**Comment by mwcraig** [comment]
One of the issues is fixed in the PR I just opened on your PR. The other I emailed about separately -- looks like astropy_helpers was left out of the sdist that was uploaded to pypi for some reason.

**Comment by mwcraig** [comment]
Well, in a sign of progress, this is a new error....

**Comment by mwcraig** [comment]
Two unrelated problems at least:
- forcing conda to install a patched version of conda-build is failing on linux 
- conda is picking up pytest-capturelog as a requirement and can't find that package.

Going to open up a separate PR to fix in hopes of getting this done tonight...

**Comment by mwcraig** [comment]
Closed -- decided a recipe template was the way to go to avoid `pytest-capturelog`. Will confirm once the packages are uploaded, but should be fixed in #9

**Pull request closed without merging**
