### PR TITLE
Update maltpynt version to 2.0

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by mwcraig** [comment]
It looks like this one now uses astropy-helpers, so it needs this added to its entry in `requirements.yml`:

```
  setup_options: '--offline'
```

The relevant line from the CI failures is https://travis-ci.org/astropy/conda-channel-astropy/jobs/141395665#L701

It happens because conda blocks downloads during builds to ensure that all dependencies have been list in the recipe (or identified from `setup.py`), and during setup astropy-helpers tries, by default, to update itself.

**Comment by bsipocz** [comment]
Thanks @mwcraig. I have to admit that didn't check what the new releases are about, just updated everything from the dashboard. 

Writing a bot to do this automatically would be a great hackday project though :)

**Comment by mwcraig** [comment]
@bsipocz I never check either!

**Comment by mwcraig** [comment]
Checking on this....

**Comment by mwcraig** [comment]
This line of the meta generated by skeleton is causing the problem:

``` yaml
  summary: '"Matteo\'s library and tools in Python for NuSTAR timing"'
```

It is the `\'` that causes the issue. Soooo...I could add a special case just for maltpynt, or scrub all recipes for that set of characters or we could add a recipe template. 

Any preference?

**Comment by bsipocz** [comment]
@mwcraig - Whichever is easiest/quickest. 
I don't think it's necessary to do it in a general way as none of the other packages has this kind of naming (which is everything but encouraging to contribute), and maybe they will change it based on the recommendations of provisional acceptance as an affiliated package.

**Comment by bsipocz** [comment]
Seriously, this package needs a sensible name as the current one is worst than a nightmare.

**Comment by mwcraig** [comment]
malt 🍻  , it passed!

Merging...

**Comment by bsipocz** [comment]
> malt 🍻 , it passed!

thanks, this helps :)

**Pull request merged**
