### PR TITLE
Update CI configurations to use conda-build-all

### PR DESCRIPTION
**Pull request by mwcraig**

### CODE REVIEW

**Comment by mwcraig** [comment]
@astrofrog -- do you have any time to look at this today? The Windows builds have gone crazy...all packages are being built, and `gammapy` is failing in a way it hasn't before.

@pelson -- do you have any idea about what might be going wrong with conda-build-all?

**Comment by bsipocz** [comment]
It picks up the gammapy v0.3 conda package. I wonder what happens if you remove that, so the builds should start from scratch?

**Comment by mwcraig** [comment]
@bsipocz -- it ultimately fails on gammapy 0.3, but the more pressing error is at https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.140/job/ic0gcx5igwc63fk2#L541 where `conda-build-all` decides that all of the packages need to be rebuilt even though they are already on the channel...

**Comment by mwcraig** [comment]
@pelson -- found the problem, 0.13.1 was never built for Windows on python 2.7/3.5. Working on fixing that.

**Comment by mwcraig** [comment]
The issue https://github.com/conda-forge/conda-build-all-feedstock/issues/12 which, ironically, I had commented on.

**Comment by mwcraig** [comment]
@bsipocz -- please do not merge this until we get some version gammapy 0.4 working in #27. I think once this is merged gammapy won't build until the import issue is worked out: https://github.com/astropy/conda-channel-astropy/pull/27#issuecomment-233141219

**Comment by mwcraig** [comment]
plus I'd like to try building an actual package with this. We should have a ccdproc release this week.

**Comment by bsipocz** [comment]
(@mwcraig - There are a few open PRs, maybe this solves the problem for one of those if you try them with it?)

**Comment by mwcraig** [comment]
Good idea, @bsipocz!

**Comment by mwcraig** [comment]
@astrofrog -- the reproject build on Windows is failing because the patches are failing. Any chance you could take a look at that?

**Comment by mwcraig** [comment]
@astrofrog -- sorry the noise, I think I can drop the patch altogether. But reproject does require numpy even though it isn't listed as a requirement....

**Comment by bsipocz** [comment]
I'm sorry, it looks like that merging #27 had introduced some conflicts with this one.

**Comment by mwcraig** [comment]
No problem, that was the easiest rebase ever!

**Comment by mwcraig** [comment]
I've got one more change I want to make before this is merged, adding the ability to to `conda-build-tools` to copy a recipe from conda-forge, if it exists. That will result in the package being copied (actually, for reproject, which is on conda-forge, it would already work that numpy is missing form its requirements).

**Comment by mwcraig** [comment]
Green lights, so I'll merge and we'll see if this copies `reproject` over to conda-channel-astropy`...

**Pull request merged**
