### PR TITLE
Update imexam version to v0.7.0

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by bsipocz** [comment]
@mwcraig - Have you seen this error before? https://travis-ci.org/astropy/conda-channel-astropy/jobs/193571209#L1107 I've run into it with several packages, but haven't got time yet to dig into it and find the cause.

**Comment by bsipocz** [comment]
Apparently it's a simple and known issue, ``conda-build`` is not yet support conda >=4.3, so pinning conda to 4.2 should solve all these building issues as of https://github.com/SciTools/conda-build-all/issues/76

**Comment by mwcraig** [comment]
This is waiting on #126 right?

**Comment by bsipocz** [comment]
Yes, and #123 should also pass with that one in.

**Pull request merged**
