### PR TITLE
Adding gala (astro-gala) version 0.1.3

### LINKED ISSUE #84: Adding gala conda build
As it's an affiliated package it would make sense for the sake of completeness to add a conda build here, too. What do you think @adrn?

### PR DESCRIPTION
**Pull request by bsipocz**
Let's see whether it works out of the box.

cc @adrn

closes #84

### CODE REVIEW

**Comment by adrn** [comment]
Hilarious -- I never changed `entry_points` in `setup.cfg`:
https://github.com/adrn/gala/blob/ffb47908cf0858cf5801abbfa01710d73643fedd/setup.cfg

**Comment by mwcraig** [comment]
You are definitely not alone in overlooking this 😀 

I have several trivial commits in affiliated packages fixing up little leftovers like this.

**Comment by bsipocz** [comment]
@adrn - https://github.com/adrn/gala/pull/63 hopefully will fix an issue. Would you tag another release that includes the fix? Otherwise we need to make a temporary recipe here.

**Comment by adrn** [comment]
@bsipocz OK, I released v0.1.3 with your commits -- see if that works? Thanks!

**Comment by bsipocz** [comment]
Merging as the appveyor failure is unrelated as we skip building gala on windows at the moment.

**Pull request merged**
