### PR TITLE
Update photutils to v0.3.1

### PR DESCRIPTION
**Pull request by larrybradley**

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @larrybradley!

**Comment by larrybradley** [comment]
The `travis` failure is due to a timeout at `continuum.io`.  I don't have permission to restart it.

**Comment by larrybradley** [comment]
The OSX builds for photutils are not in the astropy channel.  This was fixed in #137, but can you also make the photutils OSX builds now?  Thanks!

**Comment by bsipocz** [comment]
@larrybradley - Yes, they should be building now as #137 is merged.

**Comment by larrybradley** [comment]
@bsipocz OK, thanks.  I didn't know #137 would rebuild the missing packages.

**Comment by bsipocz** [comment]
Yes, the default behaviour is that it checks what to build based on the version matrices, so merging failing PRs and then fix them in master is sometimes better than hacking in a PR as it won't rebuild the package in the unaffected OS only in the failing one.

**Pull request merged**
