### PR TITLE
Adding back reproject

### PR DESCRIPTION
**Pull request by bsipocz**
reproject should be pulled from conda-forge

### CODE REVIEW

**Comment by bsipocz** [comment]
Since the python version limitation from ``requirements.yml`` still seems to be ignored, I've updated the minimum py3 version to be 3.5 in the travis file. We can change it back once the infrastructure supports it, before that I think we may see issues due to the missing py3.4 numpy 1.12 build.

**Comment by bsipocz** [comment]
@mwcraig - Could you have a look, and merge if you're happy with removing py3.4 from the versions for now?

**Comment by mwcraig** [comment]
The remaining failure appears to be during a build of the combination numpy 1.10/python 3.6 on mac. I thought at first the issue was whether there was a numpy 1.10 build for python 3.6, but that is not the problem (it is available on conda-forge). 

I'm inclined to fix it by bumping the minimum numpy version to 1.11...

I have no clue how the numpy 1.10/python 3.6 combination was built for linux.

**Comment by mwcraig** [comment]
I am fine, incidentally, with bumping the minimum python to 3.5.

**Comment by mwcraig** [comment]
giphy

Will look at first thing Wednesday morning....

**Comment by bsipocz** [comment]
No worries @mwcraig, apparently the env variable didn't have any effect as the actual command didn't use it, but a hard wired value instead.

**Pull request merged**
