### PR TITLE
Update corner version to 2.0.1

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by mwcraig** [comment]
So it looks like the requirements for corner have not changed, but it has been rearranged as a package instead of a single python file. I'm guessing that change triggered the import test in conda-build that is failing here.

@dfm -- we've been building corner for inclusion in the astropy conda channel because one of the astropy affiliated packages depends on it. Would you be amenable to adding `numpy` and `matplotlib` as install requirements in `setup` in `corner`? If not, we'll work around it here.

**Comment by bsipocz** [comment]
@mwcraig - I think the trigger was that `setup.py` in the new version has the line `import corner`.

**Comment by mwcraig** [comment]
It makes it through the build ok, though, then fails on the import test. Either way, matplotl in and numpy are hard dependencies.

**Comment by bsipocz** [comment]
I've opened a PR for it in corner.py, so maybe it's a viable solution to wait for the new release.

**Comment by dfm** [comment]
It's not the import line in the setup that causes this problem... look at that builtins magic!

Thanks for the pull request! I've merged it and pushed v2.0.1 to pypi with these deps listed in setup.py. Let me know if you need anything else. Thanks!

**Comment by mwcraig** [comment]
Thanks, @dfm! 

@bsipocz, could you please bump the corner version number when you get a chance?

**Comment by bsipocz** [comment]
Thanks @dfm!

**Pull request merged**
