### PR TITLE
Update astropy-helpers to v2.0.1

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by bsipocz** [comment]
@mwcraig - Have you seen these issues before? I've tried to add back the version pinning of conda-build, but obviously it didn't solve them.

**Comment by mwcraig** [comment]
I'll check when github comes back to life....

**Comment by mwcraig** [comment]
Yeah, this has been happening on all builds recently. I'm working on getting more recipes moved over to conda-forge.

In the short run I think we could skip building astropy-helpers. None of the packages we are currently building omit it as a submodule.

I'll take a look at conda-build-all later today.

**Comment by bsipocz** [comment]
OK, I'll try to comment out the helpers in one of the other PRs to see whether that solves the issue.

**Comment by mwcraig** [comment]
I don't think helpers will fix it...it would just mean we don't have to build it. How about if I move the other PRs over to conda-forge today?

**Comment by bsipocz** [comment]
Sure, that sounds good too.

**Comment by mwcraig** [comment]
Can we close this, @bsipocz? Think we can stop building astropy-helpers. I know @astrofrog doesn't want it moved over to conda-forge. The original reason for building it was that some affiliated packages didn't submodule helpers, but I do not believe that is still the case .

**Comment by bsipocz** [comment]
OK, let's close it and stop building them altogether. I cannot remember I saw any package use this recently, and even if they do they can always speak up.

**Pull request closed without merging**
