### PR TITLE
Adding cluster-lensing version 0.1.2

### PR DESCRIPTION
**Pull request by bsipocz**
I'm not sure this will work out of the box, but nevertheless I give it a try.

cc @jesford

### CODE REVIEW

**Comment by mwcraig** [comment]
Interesting...`conda skeleton` is generating a bad import test:

```yaml
test:
  # Python imports
  imports:
    - clusterlensing
    - clusterlensing/tests
```

Will try pushing a recipe template to your PR branch...

**Comment by mwcraig** [comment]
Opened PR on your branch

**Comment by mwcraig** [comment]
Another PR to add dependencies...

**Comment by bsipocz** [comment]
Thanks @mwcraig for fixing this.

**Comment by bsipocz** [comment]
@jesford - ``cluster-lensing`` can be now (within ~30 mins) installed with conda from the astropy channel:

``conda install -c astropy cluster-lensing``

**Pull request merged**
