### PR TITLE
Update ccdproc version to 1.2

### PR DESCRIPTION
**Pull request by mwcraig**
Please don't merge quite yet even if the CI passes...we want to a bit more testing overnight before announcing.

### CODE REVIEW

**Comment by MSeifert04** [comment]
@mwcraig Does this channel pick up new dependencies? Otherwise you might need to add `scikit-image` as dependency. 😅

**Comment by mwcraig** [comment]
@MSeifert04 -- oops, forgot ccdproc has a recipe template, thought it was using skeleton to autogenerate the recipe. Will add `scikit-image`, am curious to see whether I then hit the same fail (trying to install `dask`) that i do locally.

**Comment by MSeifert04** [comment]
hm, I thought `dask` is just an optional requirement for `scikit-image`. Why is it trying to download it? Maybe needs to be added as requirement as well? 😕

**Comment by mwcraig** [comment]
As far as I can tell, the issue is that `dask[array]` is a hard requirement for scikit-image (it is list in their requirements.txt, from which it constructs install_requires in setup.py) but the conda package does not have it listed as a dependency.

For now adding it as an explicit dependency for the ccdproc conda package...will raise issues in the appropriate places about the conda package for scikit-image.

**Comment by mwcraig** [comment]
Mostly a note to self: unclear whether dask is intended to be a hard requirement or not. `setup.py` and scikit-image.org say yes, this says no: https://github.com/scikit-image/scikit-image/blob/057448f1f439c5145fe0b42deb99240d32f5485f/DEPENDS.txt

**Comment by mwcraig** [comment]
Merging even though the OSX travis job has not completed. All other platforms are good, and I can build it locally. The OSX queue is backed up again...

**Pull request merged**
