### PR TITLE
Update to Gammapy 0.5 in requirements.yml

### PR DESCRIPTION
**Pull request by cdeil**
This PR updates Gammapy to version 0.5

I see that there's three manually maintained lists here:
https://github.com/astropy/conda-channel-astropy/blob/master/recipe_templates/gammapy/meta.yaml

- `build/entry_points`
- `test/imports`
- `test/commands`

@bsipocz @mwcraig - I guess I should update those in this PR?

Long-term: if those lists are needed, it would be better to maintain them in Gammapy instead, no?
Then we can add a a test on travis-ci that makes sure `master` is always up to date and a conda package can be built.

### CODE REVIEW

**Comment by bsipocz** [comment]
@cdeil - The recipe was added as a workaround in #27, so before updating the lists I would check first whether the build works without the recipe, using the general template. Could you please remove the whole ``recipe_templates/gammapy`` directory to check it?

**Comment by cdeil** [comment]
@bsipocz - Thanks for the tip.

I had started to update `recipe_templates/gammapy` in this branch:
https://github.com/astropy/conda-channel-astropy/compare/master...cdeil:gammapy05-v2

For now I've put aede6d1 to remove it as you suggest, let's try that first.

**Comment by mwcraig** [comment]
@cdeil -- the failure at the moment is related to this from #27 

> In addition, using a newer version of conda-build, at least some scripts are constructed incorrectly, I think because the import situation is confusing.

> One of the scripts, for example, is gammapy-info.

> The entry point that conda is constructing from setup.py is gammapy.scripts.info:info_main, but gammapy.scripts.info is both a module and a function because gammapy.scripts imports the function info from the module info.

setuptools produces a working entry point, so I'm not sure whether this should count as a conda-build bug or a setuptools feature. The recipe template skipped that import.

**Comment by cdeil** [comment]
What do you recommend I do here to get the conda build for Gammapy v0.5 working?
Continue with https://github.com/astropy/conda-channel-astropy/compare/master...cdeil:gammapy05-v2, i.e. update the files in `recipe_templates/gammapy`?

I would really like to add travis-ci builds for Gammapy that create, install and test the `sdist` and conda package. Do you have any recommendations how to add those to the build matrix? Are there other Astropy packages that do this?
We already have builds that execute make targets, so I guess adding make targets that execute a Python or shell script to do the steps would be OK?
What are the commands to execute to run the equivalent of what's done here (maybe a simplified version), i.e. create a Conda package and test it?

**Comment by bsipocz** [comment]
@cdeil - Yes, I'm afraid updating the files in ``recipe_templates/gammapy`` is the most straightforward way to proceed.
I'm not aware of any package that runs either ``sdist`` or the conda packaging on travis  as part of their CI.

**Comment by mwcraig** [comment]
@cdeil -- the easiest way to check whether the latest gammapy *release* will build with conda out of the box is this (not being used by any astropy projects, I think, but I'm doing it in at least one other project):

```
# This grabs the source from pypi and generates a recipe 
conda skeleton pypi gammapy --setup-options="--offline"
conda build gammapy
```

I imagine this could be modified to generate the skeleton from a local sdist but I haven't tried that.

**Comment by cdeil** [comment]
@bsipocz @mwcraig - Thanks!

I have to do something else this week, but plan to finish this PR and make improvements on the Gammapy side next week.

**Comment by cdeil** [comment]
I'm preparing the Gammapy 0.6 release now.
I think the issues we had here have been resolved in https://github.com/gammapy/gammapy/pull/993 and then making conda packages for 0.6 should work.

Closing this issue to make conda packages for Gammapy 0.5 now.

**Pull request closed without merging**
