### PR TITLE
Updated halotools version to v0.5

### PR DESCRIPTION
**Pull request by aphearin**
New release now up on pip

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @aphearin!

**Comment by bsipocz** [comment]
@mwcraig - Weirdly the upload is not working again, even though it was fine last week when triggered from cron.

**Comment by mwcraig** [comment]
@bsipocz - will investigate later today.

**Comment by mwcraig** [comment]
Hopefully fixed now. The issue is an API change made in anaconda-client when 1.6.3 was released (resisting temptation to rant about not following semver).

**Comment by bsipocz** [comment]
Thank  you @mwcraig!

**Pull request merged**
