### PR TITLE
Update specutils version to 0.2.2

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by mwcraig** [comment]
Md5 mismatch

**Comment by bsipocz** [comment]
There were some "try again later" errors at the top of the build too, so I'll try not to forget to restart this when leaving the office.

**Comment by mwcraig** [comment]
Ok, I'll check tonight too

**Comment by bsipocz** [comment]
it's still failing

**Comment by mwcraig** [comment]
The fail here is because the md5 checksum isn't matching. Probably needs updating in recipe template

**Comment by bsipocz** [comment]
This error is present in the other PRs but without the md5sum error. Do you think it's relevant?

https://travis-ci.org/astropy/conda-channel-astropy/jobs/149779604#L631

**Comment by mwcraig** [comment]
Apparently a pypi problem: https://groups.google.com/a/continuum.io/forum/m/?utm_medium=email&utm_source=footer#!msg/conda/Vxput-0Xok0/uHrNKnWOAAAJ

**Comment by mwcraig** [comment]
Restarting by close/reopen in hopes the issue has been fixed...

**Pull request merged**
