### PR TITLE
Update requirements.yml

### PR DESCRIPTION
**Pull request by bmorris3**
Update for the new version of astroplan.

### CODE REVIEW

**Comment by bmorris3** [comment]
Did I miss a step, @mwcraig?

**Comment by mwcraig** [comment]
Looks like something has changed in conda build...will investigate tonight. What you did was fine.

**Comment by mwcraig** [comment]
Yep, a regression was introduced when conda build 2 was released. I'll cherry pick this to a separate PR (#75) that pins conda build to an older version.

**Comment by bmorris3** [comment]
Great, thanks @mwcraig!

**Pull request closed without merging**
